<template>
  <button
    type="button"
    :class="[
      'px-2',
      'hidden',
      'text-lg',
      'font-bold',
      'bg-black',
      'rounded-3xl',
      'text-white',
      'hover:bg-gray-800',
      'group-hover/add:inline',
    ]"
  >
    +
  </button>
</template>
